spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:${DB_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${SECRET}


